{
    "port": 8080,

    "server_name": "potato annotator",

    "annotation_task_name": "Error-type annotation of GPT-4 responses to USMLE questions",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "annotation_output/simple-span-annotation-llm/",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "json", 

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
    "annotation_codebook_url": "https://docs.google.com/document/d/1tdzsD9z5FlvSYcWRXFIv_8x7wal8NiWG/edit?usp=sharing&ouid=113289196373353191964&rtpof=true&sd=true",

    "data_files": [
       "data/prolific_pilot_data_new.csv"
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text",
        "context_key": "serial_num" 
    },


    "user_config": {

      "allow_all_users": True,
      
      "users": [  ],
    },


    #the jumping-to-id function will be disabled if "jumping_to_id_disabled" is True
    "jumping_to_id_disabled": False,

    #the navigation bar will be hidden to the annotators if "hide_navbar" is True
    #"hide_navbar": True,

    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,

    "annotation_schemes": [      
        {
            "annotation_type": "highlight",
            "name": "Error category", 
            "description": "First select the error category by ticking the checkbox and then highlight the span corresponding to the error within the GPT-4 response. You can select more than one label for a given GPT-4 response; please repeat the same step as above: tick the label and then select the span. \nThe start of GPT-4 response is indicated by the following text: Annotate from here -GPT-4 Response. If there is no error, please select from the options: reasonable response by GPT-4 or cannot pick any error category.",
            "labels": [
               "Unsupported medical claim", "Non-medical factual error", "Sticking with the wrong diagnosis", "Incorrect or vague conclusion", "Ignore missing information", "Incorrect understanding of the task", "Hallucination of information", "Reasonable response by GPT-4", "Cannot pick any error category"
            ],

            # If true, numbers [1-len(labels)] will be bound to each
            # label. Highlight selection annotations with more than 10 are not supported
            # with this simple keybinding and will need to use the full item
            # specification to bind all labels to keys.
            "sequential_key_binding": True,            
        },       
    ],

    # The html that changes the visualiztation for your task. Change this file
    # to influence the layout and description of your task. This is not a full
    # HTML page, just the piece that does lays out your task's pieces
    # you may use templates in our lib, if you want to use your own template,
    # please replace the string as a path to the template
    "html_layout": "default",

    # The core UI files for Potato. You should not need to change these normally.
    #
    # Exceptions to this might include:
    # 1) You want to add custom CSS/fonts to style your task
    # 2) Your layout requires additional JS/assets to render
    # 3) You want to support additional keybinding magic
    #
    # if you want to use your own template,
    # please replace the string as a path to the template
    "base_html_template": "default",
    "header_file": "default",

    # This is where the actual HTML files will be generated
    "site_dir": "default"

}
